apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: devops-toolkit
spec:
  components:
    - name: backend
      type: worker
      properties:
        image: alpine
        cmd:
          - sleep
          - "1000000"
    - name: frontend
      type: frontend
      properties:
        name: frontend
        image: vfarcic/devops-toolkit-series
      traits:
        - type: autoscaler
          properties:
            min: 2
            max: 6
            cpuPercent: 60
        - type: ingress
          properties:
            domain: localhost
            http:
              "/": 80
